-- Run this in MySQL Workbench on your coating_guru database

ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS vehicle_make VARCHAR(100),
  ADD COLUMN IF NOT EXISTS vehicle_model VARCHAR(100),
  ADD COLUMN IF NOT EXISTS vehicle_year VARCHAR(4),
  ADD COLUMN IF NOT EXISTS vehicle_color VARCHAR(100),
  ADD COLUMN IF NOT EXISTS vehicle_regn VARCHAR(50),
  ADD COLUMN IF NOT EXISTS customer_address TEXT,
  ADD COLUMN IF NOT EXISTS customer_email VARCHAR(255),
  ADD COLUMN IF NOT EXISTS pre_amount DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_amount DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS valid_till DATE,
  ADD COLUMN IF NOT EXISTS payment_mode VARCHAR(50),
  ADD COLUMN IF NOT EXISTS warranty VARCHAR(100);

ALTER TABLE job_cards
  ADD COLUMN IF NOT EXISTS technician VARCHAR(100),
  ADD COLUMN IF NOT EXISTS time_start VARCHAR(10),
  ADD COLUMN IF NOT EXISTS time_finish VARCHAR(10),
  ADD COLUMN IF NOT EXISTS condition_rating VARCHAR(100);

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS email VARCHAR(255);
